routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::middleware(['auth'])->group(function(){
    Route::resource('company', 'CompanyController');
    Route::get('/company/edit/{id}','CompanyController@change');
    Route::get('/company/delete/{id}','CompanyController@delete');

    Route::resource('project', 'ProjectController');
    Route::get('/project/create/{company_id?}','ProjectController@create');
    Route::get('/project/edit/{id}','ProjectController@change');
    Route::get('/project/delete/{id}','ProjectController@delete');
    

    Route::post('/project/adduser/{project_id?}','ProjectController@addUser')->name('project.adduser');
    Route::resource('role', 'RoleController');
    Route::resource('task', 'TaskController');
    Route::resource('user', 'UserController');
    Route::resource('comment', 'CommentController');
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable=[
        "name",
        "description",
        "days",
        "user_id",
        "company_id",
    ];

    function users(){
        return $this->belongsToMany('app\User');
    }
    function company(){
        return $this->belongsTo('app\Company');
    }
    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\Project;
use App\ProjectUser;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth::check()){
            $project=Project::where('user_id',Auth::user()->id)->get();
            return view('project.index')->with('project',$project);
        }
        return view('auth.login');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create( $company_id =null)
    {

        $company=null;
        if(!$company_id){

            $company=Company::where('user_id',Auth::user()->id)->get();
//            return $company;
        }
        return view('project.create',['company_id'=>$company_id,'company'=>$company]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(Auth::check()){
            $project = Project::create([
                'name' => $request->input('name'),
                'description' => $request->input('description'),
                'company_id' => $request->input('company_id'),
                'user_id' => Auth::user()->id
            ]);
            if($project){
                return redirect()->route('project.show', ['project'=> $project->id])
                    ->with('success' , 'Project created successfully');
            }
        }
//        return 'hi';
        return back()->withInput()->with('error', 'Error creating new company');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        $pro=Project::find($project->id);
        $project=Project::all();
        $comment=$pro->comments;
        $data=array(
            'project'=>$pro,
            'comment'=>$comment,
        );
        return view('project.show',$data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        $com=Project::find($project->id);

        $project=Project::all();
        $data=array(
            'company'=>$com,
            'project'=>$project
        );
        return view('project.edit',$data);
    }
    public function change($id)
    {
        $com=Project::find($id);

        $project=Project::all();
        $data=array(
            'company'=>$com,
            'project'=>$project
        );
        return view('project.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
//        return $request->all();
        $projectUpdate=Project::where('id',$project->id)
            ->update([
                'name'=>$request->input(['company-name']),
                'description'=>$request->input(['description']),
            ]);
        if ($projectUpdate){
            return redirect()->route('project.show',['company'=>$project->id])
                ->with('success','Project Updated Successfully!');
        }
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        $findProject=Project::find($project->id);
        if($findProject->delete()){
            return redirect()->route('project.index')
                ->with('success','Project deleted successfully!');
        }
        return back()->withInput()->with('error','Project could not be deleted!');
    }
    function delete($id){
        $findProject=Project::find($id);
        if($findProject->delete()){
            return redirect()->route('project.index')
                ->with('success','Project deleted successfully!');
        }
        return back()->withInput()->with('error','Project could not be deleted!');
    }


    public function addUser(Request $request){
        
        $project=Project::find($request->project_id);        
        
        if(Auth::user()->id == $project->user_id){
            
            $user=User::where('email',$request->user_email)->first();
            //  $user=User::where('email','engliseng.it@gmail.com')->first();
            // dd($user);
            if($user){
                $projectUser=ProjectUser::where('user_id',$user->id)->where('project_id',$project->id)->first();
                if($projectUser){
                    return redirect()->route('project.show',['project'=>$project->id])
                        ->with('success',$request->user_email.' is already a member of this project!');
                }
            }
            
            if($project && $user){

                $project->users()->attach($user->id);
                return redirect()->route('project.show',['project'=>$project->id])
                    ->with('success',$request->user_email.' was added to the project Successfully!');
            }
        }
        return redirect()->route('project.show',['project'=>$project->id])
            ->with('error','Error adding user to the project!');

    }
}

resources/views/project/create.blade.php
@extends('layouts.app')
@section('style')
    <link rel="stylesheet" href="{{url('css/custom.css')}}">
@endsection
@section('content')
    <div class="col-md-9">
        <div class="card">
            <div class="card-header">
                Create new project
            </div>
            <div class="card-body">
                <div class="col-md-12 add-form">
                    <form method="post" action="{{route('project.store')}}">
                        {{csrf_field()}}
                        @if($company == null)
                            <input type="hidden" id="company" name="company_id" value="{{$company_id}}">
                        @endif
                        <div class="form-group">
                            <label for="exampleInputEmail1">Name<span class="required">*</span></label>
                            <input class="form-control" type="text" placeholder="Enter Name" name="name" required>
                        </div>
                        @if($company != null)
                            <div class="form-group">
                                <label for="exampleFormControlSelect1">Example select</label>
                                <select class="form-control" id="exampleFormControlSelect1" name="company_id" required>
                                    <option value="" selected disabled>Choose a company</option>
                                    @foreach($company as $item)
                                        <option value="{{$item->id}}">{{$item->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        @endif
                        <div class="form-group">
                            <label for="exampleFormControlTextarea1">Description</label>
                            <textarea required style="resize: vertical" spellcheck="false" class="form-control" id="project-content" name="description" rows="5"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
        <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
                <li><a href="/project">View Project</a></li>
            </ol>
        </div>
    </div>
@endsection

resources/views/project/edit.blade.php
@extends('layouts.app')
@section('style')
    <link rel="stylesheet" href="{{url('css/custom.css')}}">
@endsection
@section('content')
    <div class="col-md-9">
        <div class="row">
            <div class="col-md-12 add-form">
                <form method="post" action="{{route('company.update',[$company->id])}}">
                    {{csrf_field()}}
                    <input type="hidden" name="_method" value="put">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Name<span class="required">*</span></label>
                        <input class="form-control" type="text" placeholder="Enter Name" name="company-name" value="{{$company->name}}" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Description</label>
                        <textarea style="resize: vertical" spellcheck="false" class="form-control" id="company-content" name="description" rows="5">{{$company->description}}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>

        </div>
    </div>
    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
        <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
                <li><a href="/company/{{$company->id}}">View Company</a></li>
                <li><a href="/company">All Companies</a></li>
            </ol>
        </div>
    </div>
@endsection

resources/views/project/index.blade.php
@extends('layouts.app')
@section('style')
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
@endsection
@section('content')
    <div class="col-lg-8 col-md-8 offset-lg-2 offset-md-2">
        <div class="card">
            <div class="card-header">
                Project
                <a class="float-right" href="project/create"><span class="fa fa-plus" style="color: #000000;"></span></a>
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Create Date</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($project as $item)
                        <tr>
                            <th scope="row">{{$loop->iteration}}</th>
                            <td><a href="/project/{{$item->id}}">{{$item->name}}</a></td>
                            <td>{{$item->created_at->diffForHumans()}}</td>
                            <td class="text-center">
                                <a href="/project/edit/{{$item->id}}"><span class="fa fa-pencil-alt" ></span> Edit</a>
                                &nbsp;&nbsp;                    
                                <a href="#" onclick="Delete({{$item->id}})" ><span class="fa fa-trash"></span> Delete</a>
                            </td>  
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script>    
            function Delete(company_id){        
                var result = confirm('Are you sure you wish to delete this Company?');
                if( result ){
                    event.preventDefault();
                    window.location.href="/project/delete/"+company_id;                                  
                }            
            }
        </script>
@endsection

resources/views/project/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="col-md-9">
        <div class="jumbotron">
            <div class="container">
                <h1 class="display-5">{{$project->name}}</h1>
                <p>{{$project->description}}</p>
            </div>
        </div>
        @include('partial.comment')
        <br>
        <form method="post" action="{{route('comment.store')}}">
            {{csrf_field()}}
            <input type="hidden" name="commentable_type" value="app\Project">
            <input type="hidden" name="commentable_id" value="{{$project->id}}">

            <div class="form-group">
                <label for="exampleFormControlTextarea1">Comment</label>
                <textarea style="resize: vertical" spellcheck="false" class="form-control" id="comment-content" name="body" rows="3" placeholder="Enter comment"></textarea>
            </div>
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Proof of work done (Url/Photos)</label>
                <textarea style="resize: vertical" spellcheck="false" class="form-control" id="comment-content" name="url" rows="2" placeholder="Enter url or screenshots"></textarea>
            </div>
            <button type="submit" class="btn btn-primary mb16">Submit</button>
        </form>
    </div>

    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
        <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
                <li><a href="/project/{{$project->id}}/edit">Edit</a></li>
                <li><a href="/project/create">Add project</a></li>
                <li><a href="/project">View projects</a></li>
                {{--<li><a href="/project/create">Create new project</a></li>--}}
                <hr>
                @if($project->user_id==Auth::user()->id)
                    <li>
                        <a href="#" onclick="
                            var result = confirm('Are you sure you wish to delete this project?');
                                if( result ){
                                      event.preventDefault();
                                      document.getElementById('delete-form').submit();
                                }
                            ">Delete
                        </a>

                        <form id="delete-form" action="{{ route('project.destroy',[$project->id]) }}"
                              method="POST" style="display: none;">
                            <input type="hidden" name="_method" value="delete">
                            {{ csrf_field() }}
                        </form>
                    </li>
                @endif
                {{--<li><a href="#">Add new user</a></li>--}}
            </ol>
        </div>
        <br>
        <div class="sidebar-module">
            <h4>Add memeber</h4>
            <ol class="list-unstyled">
                <li>
                    <form id="add-user-form" action="{{ route('project.adduser') }}" method="POST">
                        <input type="hidden" id="project_id" name="project_id" value="{{$project->id}}">
                        {{ csrf_field() }}

                        <div class="input-group mb-3">
                            <input required name="user_email" type="email" class="form-control" placeholder="Enter email" aria-label="Add member" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" type="submit">Add</button>
                            </div>
                        </div>
                    </form>

                </li>
            </ol>
        </div>
        <br>
        <div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
                @foreach($project->users as $item)
                    <li>
                        <a href="#">{{$item->email}}</a>
                    </li>
                @endforeach

            </ol>
        </div>
    </div>
@endsection