routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::middleware(['auth'])->group(function(){
    Route::resource('company', 'CompanyController');
    Route::get('/company/edit/{id}','CompanyController@change');
    Route::get('/company/delete/{id}','CompanyController@delete');

    Route::resource('project', 'ProjectController');
    Route::get('/project/create/{company_id?}','ProjectController@create');
    Route::get('/project/edit/{id}','ProjectController@change');
    Route::get('/project/delete/{id}','ProjectController@delete');
    

    Route::post('/project/adduser/{project_id?}','ProjectController@addUser')->name('project.adduser');
    Route::resource('role', 'RoleController');
    Route::resource('task', 'TaskController');
    Route::resource('user', 'UserController');
    Route::resource('comment', 'CommentController');
});

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable=[
        "name",
        "description",
        "user_id",
    ];
    function user(){
        return $this->belongsTo('app\User');
    }
    public function projects(){
        return $this->hasMany('app\Project');
    }
    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\Project;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // return 'hi';
        if(Auth::check()){
            $company=Company::where('user_id',Auth::user()->id)->get();
            return view('company.index')->with('company',$company);
        }
        return view('auth.login');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(Auth::check()){
            $company = Company::create([
                'name' => $request->input('name'),
                'description' => $request->input('description'),
                'user_id' => Auth::user()->id
            ]);
            if($company){
                return redirect()->route('company.show', ['company'=> $company->id])
                    ->with('success' , 'Company created successfully');
            }
        }
//        return 'hi';
        return back()->withInput()->with('error', 'Error creating new company');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        $com=Company::find($company->id);
    
        $project=Project::all();
        $data=array(
            'company'=>$com,
        );
        return view('company.show',$data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        $com=Company::find($company->id);

        $project=Project::all();
        $data=array(
            'company'=>$com,
            'project'=>$project
        );
        return view('company.edit',$data);
    }
    public function change($id)
    {
        $com=Company::find($id);

        $project=Project::all();
        $data=array(
            'company'=>$com,
            'project'=>$project
        );
        return view('company.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Company $company)
    {
//        return $request->all();
        $companyUpdate=Company::where('id',$company->id)
                                ->update([
                                    'name'=>$request->input(['company-name']),
                                    'description'=>$request->input(['description']),
                                ]);
        if ($companyUpdate){
            return redirect()->route('company.show',['company'=>$company->id])
                             ->with('success','Company Updated Successfully!');
        }
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {    
        $findCompany=Company::find($company->id);    
        $project=Project::where('company_id',$company->id)->delete();        
        if($findCompany->delete()){                    
            return redirect()->route('company.index')
                ->with('success','Company deleted successfully!');
        }
        return back()->withInput()->with('error','Company could not be deleted!');
    }
    function delete($id){
        $findCompany=Company::find($id);    
        $project=Project::where('company_id',$id)->delete();        
        if($findCompany->delete()){                    
            return redirect()->route('company.index')
                ->with('success','Company deleted successfully!');
        }
        return back()->withInput()->with('error','Company could not be deleted!');
    }
}

resources/views/company/create.blade.php
@extends('layouts.app')
@section('style')
    <link rel="stylesheet" href="{{url('css/custom.css')}}">
@endsection
@section('content')
    <div class="col-md-9">
        <div class="card">
            <div class="card-header">
                Create new company
            </div>
            <div class="card-body">
                <div class="col-md-12 add-form">
                    <form method="post" action="{{route('company.store')}}">
                        {{csrf_field()}}
                        <div class="form-group">
                            <label for="exampleInputEmail1">Name<span class="required">*</span></label>
                            <input class="form-control" type="text" placeholder="Enter Name" name="name" required>
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlTextarea1">Description</label>
                            <textarea required style="resize: vertical" spellcheck="false" class="form-control" id="project-content" name="description" rows="5"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
        <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
                <li><a href="/company">View Company</a></li>
            </ol>
        </div>
    </div>
@endsection

resources/views/company/edit.blade.php
@extends('layouts.app')
@section('style')
    <link rel="stylesheet" href="{{url('css/custom.css')}}">
@endsection
@section('content')
    <div class="col-md-9">
        <div class="row">
            <div class="col-md-12 add-form">
                <form method="post" action="{{route('company.update',[$company->id])}}">
                    {{csrf_field()}}
                    <input type="hidden" name="_method" value="put">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Name<span class="required">*</span></label>
                        <input class="form-control" type="text" placeholder="Enter Name" name="company-name" value="{{$company->name}}" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Description</label>
                        <textarea style="resize: vertical" spellcheck="false" class="form-control" id="company-content" name="description" rows="5">{{$company->description}}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>

        </div>
    </div>
    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
        <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
                <li><a href="/company/{{$company->id}}">View Company</a></li>
                <li><a href="/company">All Companies</a></li>
            </ol>
        </div>
    </div>
@endsection

resources/views/company/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="col-lg-8 col-md-8 offset-lg-2 offset-md-2">
        <div class="card">
            <div class="card-header">
                Company
                <a class="float-right" href="company/create"><span class="fa fa-plus" style="color: #000000;"></span></a>
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Create Date</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($company as $item)
                        <tr>
                            <th scope="row">{{$loop->iteration}}</th>
                            <td><a href="/company/{{$item->id}}">{{$item->name}}</a></td>
                            <td>{{$item->created_at->diffForHumans()}}</td>
                            <td class="text-center">
                                <a href="/company/edit/{{$item->id}}"><span class="fa fa-pencil-alt" ></span> Edit</a>
                                &nbsp;&nbsp;                    
                                <a href="#" onclick="Delete({{$item->id}})" ><span class="fa fa-trash"></span> Delete</a>
                            </td>                        
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script>    
        function Delete(company_id){        
            var result = confirm('Are you sure you wish to delete this Company?');
            if( result ){
                event.preventDefault();
                window.location.href="/company/delete/"+company_id;                                                  
            }            
        }
    </script>
@endsection

resources/views/company/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="col-md-9">
        <div class="jumbotron">
            <div class="container">
                <h1 class="display-5">{{$company->name}}</h1>
                <p>{{$company->description}}</p>
                {{--<p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>--}}
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                Projects
                <a class="float-right" href="company/create"><span class="fa fa-plus" style="color: #000000;"></span></a>
            </div>
            <div class="card-body">
                @foreach($company->projects as $item)
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">{{$item->name}}</h3>
                            <p class="card-text">{{$item->description}}</p>
                            <a href="/project/{{$item->id}}" class="btn btn-primary">View Detail</a>
                        </div>
                    </div><br>
                @endforeach
            </div>
        </div>
    </div>
    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
        <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
                <li><a href="/company/{{$company->id}}/edit">Edit</a></li>
                <li><a href="/project/create/{{$company->id}}">Add project</a></li>
                <li><a href="/company">View companies</a></li>
                <li><a href="/company/create">Create new company</a></li>
                <hr>
                <li>
                    <a href="#" onclick="
                        var result = confirm('Are you sure you wish to delete this Company?');
                            if( result ){
                                  event.preventDefault();
                                  document.getElementById('delete-form').submit();
                            }
                        ">Delete
                    </a>
                    <form id="delete-form" action="{{ route('company.destroy',[$company->id]) }}"
                          method="POST" style="display: none;">
                        <input type="hidden" name="_method" value="delete">
                        {{ csrf_field() }}
                    </form>
                </li>
                {{--<li><a href="#">Add new user</a></li>--}}
            </ol>
        </div>
    </div>
@endsection